export * from "./Register/Registerpt1/Registerpt1"
export * from "./Register/Registerpt2/Registerpt2"
export * from "./RoomById/RoomById"
export * from "./RoomSearch/RoomSearch"
export * from "./Pruebas/MapCreation"
export * from "./Pruebas/ByIdMap"